version: '3.8'

services:
  computation-game:
    container_name: computation-game-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
